name: Test
on:
  push:
    branches:
      - main


jobs:
  do-some-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Image Tag
        id: get-tag
        run: |
          echo "IMAGE_TAG=$(git describe --tags --abbrev=0)"
          echo "IMAGE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Check Image Tag
        run: |
          echo ${{ steps.get-tag.outputs.IMAGE_TAG }}

