name: Test
on:
  push:
    branches:
      - main


jobs:
  do-some-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Image Tag
        id: get-tag
        run: |
          REV=$(git rev-list --tags --max-count=1)
          IMAGE_TAG=$(git describe --tags $REV)
          echo "IMAGE_TAG=$(IMAGE_TAG)"
          echo "IMAGE_TAG=$(IMAGE_TAG)" >> $GITHUB_OUTPUT

      - name: Check Image Tag
        run: |
          echo ${{ steps.get-tag.outputs.IMAGE_TAG }}

